### ISSUE TITLE
Fix typos and broken links

### ISSUE THREAD

**Issue by samwarwick** [TokenScript/documents#17]
The documentation at https://tokenscript.org/ needs to be checked for typos and broken/deprecated links.

Some example typos from https://tokenscript.org/QuickStart.html:

- Quick Start (**usuable** now)
- Before we start to create your own Action Card, you should have a **loot** to the JavaScript file about.en.js. It contains instructions for the wallet how to **unterstand** the about Action Card.
- If the make **commaned** doesn't work, you might lack some software

Example broken link from https://tokenscript.org/guides/Miniguide-deploy-token-on-ropsten.html:

- "browse to Ethereum Studio" navigates to https://ethereum.org/en/studio/ which has a sunset message stating "Ethereum Studio is no longer actively maintained"

**Comment by weiwu-zhang** [comment]
keeping this for typos, Split other issues into #18 and #19. Thanks.
